name: Node.js CI

on:
  push:
    branches:
      - master  # Le workflow se déclenche lors de push sur la branche 'master'
  pull_request:
    branches:
      - master  # Le workflow se déclenche lors de pull requests vers 'master'

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser un runner basé sur Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Cloner le code du repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Choisir la version de Node.js (ex: 14)

    - name: Install dependencies
      run: npm install  # Installer les dépendances avec npm

    - name: Run tests
      run: npm test  # Lancer les tests (en utilisant Jest par exemple)
